FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/routes/cust.py
from flask import Blueprint, render_template, request, redirect, session, url_for
from flask_login import login_required, logout_user
import ibm_db
from .views import conn, pass_regex, mail
import uuid
from datetime import date, datetime
import re
import hashlib


QUERY_STATUS_OPEN = "OPEN"
QUERY_STATUS_ASSIGNED_AGENT = "AGENT ASSIGNED"
QUERY_STATUS_CLOSE = "CLOSE"

cust = Blueprint("customer", __name__)

@cust.route('/customer/')
@login_required
def profile():
    '''
        Custome can see his/her profile card
    '''
    from .views import customer
        
    if hasattr(customer, 'uuid'):
        return render_template('cust profile.html', customer = customer, id = 0)

    else:
        return redirect(url_for('blue_print.logout'))

@cust.route('/customer/new', methods = ['GET', 'POST'])
@login_required
def new():
    '''
        Customer can create a new ticket 
    '''
    from .views import customer

    if(hasattr(customer, 'uuid')):
        if request.method == 'POST':
            # collecting the query entered by the customer in the textarea
            query = request.form.get('query-box')

            msg = ""
            to_show = False

            if(len(query) == 0):
                msg = "Query cannot be empty!"
                to_show = True

            else:
                # updating the query in the database
                update_query = '''
                    INSERT INTO tickets 
                        (ticket_id, raised_by, raised_on, issue, query_status)
                    VALUES 
                        (?, ?, ?, ?, ?)
                '''

                try:
                    stmt = ibm_db.prepare(conn, update_query)

                    # creating a uuid for the ticket_id
                    ticket_id = str(uuid.uuid4())
                    raised_by = customer.uuid
                    raied_on = datetime.now()

                    ibm_db.bind_param(stmt, 1, ticket_id)
                    ibm_db.bind_param(stmt, 2, raised_by)
                    ibm_db.bind_param(stmt, 3, raied_on)
                    ibm_db.bind_param(stmt, 4, query)
                    ibm_db.bind_param(stmt, 5, QUERY_STATUS_OPEN)

                    ibm_db.execute(stmt)

                    msg = "Ticket created!"
                    to_show = True

                    send_email = session['EMAIL']

                    # sending the acknowledgement mail to the customer
                    mail.sendEmail(
                        f'Customer Care Registry', 
                        f'''Welcome {session['FIRST_NAME']}! <br/>
                            You have created a new ticket! <br/>
                            Ticket ID : <strong>{ticket_id}</strong> <br/>
                            Query : <strong>{query}</strong> <br/> <br/>
                            <br/>
                            An agent will be assigned to you very soon!! <br/>
                            Stay Tuned...''',
                        [f'{send_email}']
                    )

                except:
                    msg = "Something went wrong!"
                    to_show = True

            return render_template('cust new ticket.html', id = 1, to_show = to_show, message = msg)

        return render_template('cust new ticket.html', id = 1)

    else:
        # logging out
        return redirect(url_for('blue_print.logout'))

@cust.route('/customer/tickets')
@login_required
def tickets():
    '''
        Fetching all the tickets raised by the customer
    '''
    from .views import customer

    if(hasattr(customer, 'uuid')):
        fetch_query = '''
            SELECT  
                tickets.ticket_id,
                tickets.raised_on,
                tickets.query_status,
                agent.first_name, 
                tickets.issue,
                tickets.raised_by
            FROM
                tickets
            LEFT JOIN 
                agent ON agent.agent_id = tickets.assigned_to 
            ORDER BY tickets.raised_on DESC
        '''

        from .views import customer
        raised_by = customer.uuid

        try:
            stmt = ibm_db.prepare(conn, fetch_query)
            ibm_db.execute(stmt)

            tickets = ibm_db.fetch_assoc(stmt)
            tickets_list = []

            if tickets:
                # means, the customer has raised some tickets before
                while tickets != False:
                    if raised_by == tickets['RAISED_BY']:
                        temp = []

                        temp.append(tickets['TICKET_ID'])
                        temp.append(str(tickets['RAISED_ON'])[0:10])
                        temp.append(tickets['QUERY_STATUS'])
                        temp.append(tickets['ISSUE'])
                        temp.append(tickets['FIRST_NAME'])

                        tickets_list.append(temp)                       

                    tickets = ibm_db.fetch_assoc(stmt)

                return render_template(
                    'cust tickets.html',
                    id = 2,
                    tickets_to_show = True,
                    tickets = tickets_list,
                    msg = "These are your tickets"
                )

            else:
                # means, the customer is yet to raise a ticket
                return render_template(
                    'cust tickets.html',
                    id = 2,
                    tickets_to_show = False,
                    msg = "You are yet to rise a ticket"
                )

        except:
            # something fishy happened while loading the customer's tickets
            return render_template(
                'cust tickets.html',
                id = 2,
                to_show = True,
                message = "Something went wrong! Please Try Again"
            )

    else:
        # logging out
        return redirect(url_for('blue_print.logout'))
    
@cust.route('/customer/change', methods = ['GET', 'POST'])
@login_required
def change():
    '''
        Changing the password of the customer
    '''
    from .views import customer
    
    if hasattr(customer, 'first_name'):
        if request.method == 'POST':
            # getting the passwords entered by the customer
            password = request.form.get('password')
            new1 = request.form.get('new-pass-1')
            new2 = request.form.get('new-pass-2')

            msg = ""
            to_show = False

            # validating the passwords entered by the ucer
            if((len(password) or len(new1) or len(new2)) < 8):
                password = new1 = new2 = ""
                msg = "Passwords must be atleast 8 characters long!!" 
                to_show = True     

            elif new1 != new2:
                password = new1 = new2 = ""
                msg = "Passwords do not match" 
                to_show = True

            elif password == new1:
                password = new1 = new2 = ""
                msg = "Old and New passwords cannot be same" 
                to_show = True

            elif (not (re.fullmatch(pass_regex, new1))):
                password = new1 = new2 = ""
                msg = "Enter a valid password"
                to_show = True

            # by here the passwords are evaluated
            if not to_show:
                # updating the password of the customer
                # only if, the existing password of the user is valid
                # checking that if is true the database

                # query tp get the existing encrypted password of the customer
                get_password_sha = '''
                    SELECT passcode FROM customer WHERE cust_id = ?
                '''

                try:
                    stmt = ibm_db.prepare(conn, get_password_sha)
                    ibm_db.bind_param(stmt, 1, customer.uuid)
                    ibm_db.execute(stmt)

                    existing = ibm_db.fetch_assoc(stmt)['PASSCODE']

                    # checking 
                        # if the existing encrypted password is equal to
                        # the encrypted one of the one
                    # that is enetered by the customer
                    
                    # passwords match
                    if (existing == str(hashlib.sha256(password.encode()).hexdigest())):
                        # updating the password of the customer

                        # query to update the password
                        update_password_query = '''
                            UPDATE customer SET passcode = ? WHERE cust_id = ?
                        '''

                        # enrcypting the new password entered by the user
                        enc = str(hashlib.sha256(new1.encode()).hexdigest())

                        change = ibm_db.prepare(conn, update_password_query)
                        ibm_db.bind_param(change, 1, enc)
                        ibm_db.bind_param(change, 2, customer.uuid)

                        ibm_db.execute(change)

                        send_mail = session['EMAIL']

                        # sending the acknowledgement mail to the customer
                        mail.sendEmail(
                            f'Customer Care Registry', 
                            f'''Welcome {session['FIRST_NAME']}! <br/>
                                It seems you have changed your password! <br/>
                                If it is not you, kindly report to us <br/>
                                Thank you!!
                            ''',
                            [f'{send_mail}']
                        )

                        # password is changed
                        # now logging out the customer and re-directing to login page
                        logout_user()
                        session.clear()
                        
                        return render_template(
                            'login.html',
                            email = customer.email,

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/address.html
{% extends 'base.html' %}

{% block title %}
    Address Column
{% endblock %}

{% block main %}
    <div class="dashboard-div">
        <nav>
            <div class="dash-nav">
                <div>
                    <div class="dash-img-text">
                        {% if user == "AGENT" %}
                            <a href="{{ url_for('agent.assigned') }}">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                            <img src="{{ url_for('static', filename='images/cust profile.png') }}" class="img-in-nav" alt="logo"/>
                        {% else %}
                            <a href="{{ url_for('customer.tickets') }}">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                            <img src="{{ url_for('static', filename='images/agent.png') }}" class="img-in-nav" alt="logo"/>
                        {% endif %}
                        <h3>{{ name }}</h3>
                    </div>
                </div>
                <div>
                    <div style="align-items: center;">
                        {% if value == "True" %}
                            {% if user == "CUSTOMER" %}
                                <a href="/customer/close/{{ id }}"><button class="logout-btn">CLOSE TICKET</button></a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        <div class="chat-body">
            <div class="chat-contents" id="content">
                {% if msgs_to_show %}
                    {% for chat in chats %}
                        {% if chat['SENDER_ID'] == sender_id %}
                            <div class="message-sent">{{ chat['MESSAGE'] }}</div>
                        {% else %}
                            <div class="message-sent received">{{ chat['MESSAGE'] }}</div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
            <div class="chat-input-div">
                {% if value == "True" %}
                    <form method="POST" action="{{ post_url }}">
                        <input name="message-box" class="chat-input" type="text" placeholder="Type something" required/>
                        <button type="submit" class="chat-send">
                            <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                        </button>
                    </form>
                {% else %}
                    <div>
                        {% if user == "CUSTOMER" %}
                            <h4>You closed this ticket. Chats are disabled</h4>
                        {% else %}
                            <h4>{{ name }} closed this ticket. Chats are disabled</h4>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/admin acc agent.html
{% extends 'admin dashboard.html' %}

{% block title %}
    ALL_REQUESTS
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/admin dashboard.html
{% extends 'dashboard.html' %}

{% block left %}
    <div class="links-left-div" onload="highlight()">
        <ul id="dash-parent-list">
            <li> 
                <a href="{{ url_for('admin.tickets') }}">
                    <div class="link-items">
                        <div><i class="fa fa-ticket" aria-hidden="true"></i></div>
                        <h2>TICKETS</h2>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.agents') }}">
                    <div class="link-items">
                        <div><i class="fa fa-user" aria-hidden="true"></i></div>
                        <h2>AGENTS</h2>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.accept') }}">
                    <div class="link-items">
                        <div><i class="fa fa-question" aria-hidden="true"></i></div>
                        <h2>REQUESTS</h2>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.about') }}">
                    <div class="link-items">
                        <div><i class="fa fa-info" aria-hidden="true"></i></div>
                        <h2>ABOUT</h2>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.support') }}">
                    <div class="link-items">
                        <div><i class="fa fa-comments-o" aria-hidden="true"></i></div>
                        <h2>FEEDBACK</h2>
                    </div>
                </a>
            </li>
        </ul>
    </div>

    <script>
        window.onload = function highlight(){
            id = '{{ id }}'
            var element = document.getElementById('dash-parent-list').children.item(id);
            element.className = "active";
            console.log("function called")
        }
    </script>
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/admin support.html
{% extends 'admin dashboard.html' %}

{% block title %}
    FEEDBACK
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/agent about.html
{% extends 'agent dashboard.html' %}

{% block title %}
    ABOUT
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/agent no show.html
{% extends 'base.html' %}

{% block title %}
    Welcome {{ agent.first_name }}!
{% endblock %}

{% block main %}
    <div class="agent-no-show">
        <form method="GET" action="{{ url_for('blue_print.logout') }}">
            <img class="no-show-img" src="../static/images/cart logo white-modified.png" alt="logo"/>
            <h2 class="no-show-header">Welcome agent, {{ agent.first_name }}</h2>
            <p>It seems your account is not yet verified by the admin! So would you please login after a while.</p>
            <button class="logout-btn" type="submit">LOGOUT</button>
        </form>
    </div>
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <!-- Linking css, js, Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/pass.js') }}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Linking Watson Assistant -->
    {% block watson %}
    {% endblock %}
</head>
<body>
    {% block alert%}
        {% if to_show %}
            <script>
                alert('{{ message }}')
            </script>
        {% endif %}
    {% endblock %}

    {% block main %}
    {% endblock %}
</body>
</html>

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/cust about.html
{% extends 'cust dashboard.html' %}

{% block title %}
    ABOUT
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/cust change.html
{% extends 'cust dashboard.html' %}

{% block title %}
    CHANGE_PASSWORD
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/cust dashboard.html
{% extends 'dashboard.html' %}

{% block left %}
    <div class="links-left-div">
        <ul  id="dash-parent-list">
            <li>
                <a href="{{ url_for('customer.profile') }}">
                    <div class="link-items">
                        <div><i class="fa fa-user" aria-hidden="true"></i></div>
                        <h2>PROFILE</h2>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.tickets') }}">
                    <div class="link-items">
                        <div><i class="fa fa-ticket" aria-hidden="true"></i></div>
                        <h2>TICKETS</h2>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.new') }}">
                    <div class="link-items">
                        <div><i class="fa fa-plus" aria-hidden="true"></i></div>
                        <h2>NEW_TICKET</h2>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.change') }}">
                    <div class="link-items">
                        <div><i class="fa fa-key" aria-hidden="true"></i></div>
                        <h2>CHANGE_PASSWORD</h2>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.about') }}">
                    <div class="link-items">
                        <div><i class="fa fa-info" aria-hidden="true"></i></div>
                        <h2>ABOUT</h2>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.support') }}">
                    <div class="link-items">
                        <div><i class="fa fa-comments-o" aria-hidden="true"></i></div>
                        <h2>FEEDBACK</h2>
                    </div>
                </a>
            </li>
        </ul>
    </div>

    <script>
        window.onload = function highlight(){
            id = '{{ id }}'
            var element = document.getElementById('dash-parent-list').children.item(id);
            element.className = "active";
            console.log("function called")
        }
    </script>
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/cust support.html
{% extends 'cust dashboard.html' %}

{% block title %}
    SUPPORT
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/dashboard.html
{% extends 'base.html' %}

{% block main %}
    <div class="dashboard-div">
        <nav>
            <div class="dash-nav">
                <div>
                    <div class="dash-img-text">
                        <img src="../static/images/cart logo white-modified.png" class="img-in-nav" alt="logo"/>
                        <h2>Customer_Care_Registry</h2>
                    </div>
                </div>
                <div>
                    <div class="online-div" onclick="showSettings()">
                        <img src="../static/images/cust.png" class="img-in-nav" alt="logo"/>
                    </div>
                </div>
            </div>
        </nav>
        
        <div class="dash-body">
            <div class="dash-left">
                {% block left %}
                {% endblock %}
            </div>
            <div class="dash-right">
                {% block right %}
                {% endblock %}
            </div>
        </div>

        <div class="settings-menu" id="settings-menu" style="visibility: hidden;">
            <div>
                <p> You Want to Logout?</p>
                <a href="{{ url_for('blue_print.login') }}">
                    <button class="logout-btn" type="button">Logout</button>
                </a>
            </div>
        </div>
    </div>

    <script>
        function showSettings(){
            var settings = document.getElementById("settings-menu");

            settings.style.visibility = settings.style.visibility == "hidden" ? "visible" : "hidden";
        }
    </script>
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/forget.html
{% extends 'base.html' %}

{% block title %}
    Forgot Password?
{% endblock %}

{% block main %}
    <div class="bg-main-div">
        <section class="login-section extra">
            <div class="login-div">
                <div class="login-header">
                    <img src="{{ url_for('static', filename='images/cart logo white.png') }}" class="login-img" alt="logo" />
                    <h2>Forgot Password?</h2>
                    <p>Use your Registry Account</p>
                </div>
                <div class="login-remind">
                    <form action="{{ url_for('blue_print.forgot') }}" method="POST" class="login-form">
                        <label>Email</label>
                        <input type="email" required name="email" placeholder="Enter your email"/>
                        
                        <div class="role-div">
                            <p>Role : </p>
                            <div>
                                <div>
                                    <input type="radio" style="height: 20px;" value="Customer" checked name="role-check"/>
                                    <p>Customer</p>
                                </div>
                                <div>
                                    <input type="radio" style="height: 20px;" value="Agent" name="role-check"/>
                                    <p>Agent</p>
                                </div>
                            </div>
                        </div>
    
                        <button class="submit-btn" type="submit">Get Code</button>
    
                        <div>
                            <a href="{{ url_for('blue_print.login') }}" class="links">Signin instead</a> <br> 
                            <div>
                                <a href="{{ url_for('blue_print.register') }}" class="links">Don't have an account yet? Register</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

FINAL_DELIVERIES/CUSTOMER_CARE_REGISTRY/registry/templates/register.html
{% extends 'base.html' %}

{% block title %}
    Register
{% endblock %}

{% block main %}
    <section class="register-section">
        <div class="register-left">
            <h1>Create your Registry Account</h1>

            <form action="{{ url_for('blue_print.register') }}" method="POST">
                <div class="reg-left-input-div">
                    <div>
                        <label>First Name</label>
                        <input type="text" value="{{ first_name }}" placeholder="First Name" name="first_name" />
                    </div>
                    <div>
                        <label>Last Name</label>
                        <input type="text" value="{{ last_name }}" placeholder="Last Name" name="last_name" />
                    </div>
                </div>
    
                <div class="email-reg">
                    <label>Email</label>
                    <input type="email" value="{{ email }}" placeholder="Your email address" name="email" />
                    <p>This will be your Registry account email</p>
                </div>
    
                <div class="role-div">
                    <p>Role : </p>
                    <div>
                        <div style="margin-top: 0px;">
                            <input type="radio" style="height: 20px;" value="Customer" checked name="role-check"/>
                            <p>Customer</p>
                        </div>
                        <div style="margin-top: 0px;">
                            <input type="radio" style="height: 20px;" value="Agent" name="role-check"/>
                            <p>Agent</p>
                        </div>
                    </div>
                </div>
    
                <div class="reg-left-input-div">
                    <div>
                        <label>Password</label>
                        <input type="password" id="password-input"  value="{{ password }}" placeholder="Password" name="password" />
                    </div>
                    <div>
                        <label>Confirm Password</label>
                        <input type="password" id="password-input1"  value="{{ confirm_password }}" placeholder="Confirm password" name="confirm_password" />
                    </div>
                </div>
                <p>Use 8 or more characters with a mix of just letters and numbers</p>
    
                <div class="show-pass-div">
                    <input type="checkbox" onclick="showPassword()" name="show password check"/>
                    <p>Show Password</p>
                </div>
    
                <div class="sign-instead-div">
                    <a href="{{ url_for('blue_print.login') }}" class="cust-link">Sign-in instead</a>
                    <button type="submit" class="submit-btn submit-1">Register</button>
                </div>
            </form>
        </div>
        <div class="register-right">
            <img src="{{ url_for('static', filename='images/cart logo white.png') }}" alt="logo"/>
            <h1>Politeness goes far, yet costs nothing</h1>
        </div>
    </section>
{% endblock %}